FROM debian:latest

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get dist-upgrade -y
RUN apt autoremove -y

#RUN apt-get install php -y

#RUN apt-get install gnupg2 -y
#RUN apt-get install curl -y

# # MYSQL
#RUN docker-php-ext-configure pdo_mysql
#RUN docker-php-ext-configure opcache
#RUN docker-php-ext-install pdo_mysql

#RUN docker-php-ext-configure pdo_mysql
#RUN docker-php-ext-configure opcache
